name: beldex_browser
description: An app to interact with the Belnet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+4

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  belnet_lib:
    path: ./belnet_lib
  # shared_preferences: ^2.0.15
  # flutter_svg: ^1.1.4
  # provider: ^6.0.3
  # awesome_notifications: any #^0.6.21
  lottie: any #^3.3.1
  # connectivity_plus: ^2.3.6+1
  # #new_version: ^0.3.1
  # #in_app_update: any
  # get: any
  # #native_updater: any #^0.1.0
  # #syncfusion_flutter_charts: ^20.3.49
  # flutter_riverpod: any
  # #fl_chart: ^0.55.2
  # clipboard: any
  # charts_painter: ^2.0.0+2
  # elapsed: any
  # http: any
  # flutter_charts: any
  # url_launcher: ^6.1.7
  # intl: any
  # chart_sparkline: ^1.0.11
  # percent_indicator: ^4.2.2
  # flutter_sinusoidals:
#  url_launcher: ^6.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  #charts_flutter: ^0.12.0
  
# For material you.
  dynamic_color: ^1.7.0
  upgrader: ^11.4.0
  flutter_inappwebview: 6.0.0  # ^6.0.0-beta.30
  flutter_downloader: ^1.12.0 #1.11.5
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  provider: ^6.1.5
  share_plus: ^11.0.0
  #share_extend: ^2.0.0
  # charts_flutter: ^0.9.0
  crypto: ^3.0.6
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
#  flutter_icons: ^1.1.0
  flutter_font_icons: ^2.2.7
  flutter_svg: ^2.2.0
  mime: ^2.0.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.3.1
  flutter_colorpicker: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  collection: #^1.19.1
  
  #webview_flutter: ^4.2.4
  #in_app_update: ^4.2.3
  flutter_switch: ^0.3.2
  #flutter_windowmanager:
  square_progress_indicator: ^0.0.8
  
  get: ^4.7.2
  #flutter_file_downloader: ^2.1.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.12
  #flutter_local_notifications: ^19.3.1
  flutter_typeahead: ^5.2.0 #^5.0.2

  logging: ^1.3.0
  square_percent_indicater: ^0.1.0
# need to remove just for testing purpose
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.4
 
  http: any

  #receive_sharing_intent: ^1.8.1
  
  installed_apps: ^1.5.1


  velocity_x: ^4.3.1
  
  flutter_markdown: any
 
  typewritertext: ^3.0.9
 

  get_it: ^8.0.3
  dio: ^5.8.0+1
 
  loading_animation_widget: ^1.3.0

  listen_sharing_intent: ^1.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/appicon_browser.png"
  ios: true
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/appicon_browser.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/images/flags/
    - assets/images/ai-icons/
    # - assets/images/Belnet_Text_White.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
